/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParser.java */
import db.*;
import java.util.*;

public class SimpleDBMSParser implements SimpleDBMSParserConstants {
  private static SimpleDBMS dbms = new SimpleDBMS();

  public static void main(String args[]) throws ParseException, ErrorException
  {
    SimpleDBMSParser parser = new SimpleDBMSParser(System.in);
    System.out.print("DB_2013-11422> ");

    while (true)
    {
      try
      {
        parser.command();
      }
      catch (ParseException e)
      {
        PrintMessages p = new PrintMessages(Flags.SYNTAX_ERROR);
        p.print();
        SimpleDBMSParser.ReInit(System.in);
      }
      catch (ErrorException e)
      {
        e.p.print();
        SimpleDBMSParser.ReInit(System.in);
      }
    }
  }

// grammar file Í∑∏Î?Î°? Íµ¨ÌòÑ
  static final public void command() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CREATE_TABLE:
    case DROP_TABLE:
    case DESC:
    case INSERT:
    case DELETE:
    case SELECT:
    case SHOW_TABLES:
      queryList();
      break;
    case EXIT:
      jj_consume_token(EXIT);
      jj_consume_token(SEMICOLON);
      dbms.close();
      System.exit(0);
      break;
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void queryList() throws ParseException {
                     PrintMessages p;
    label_1:
    while (true) {
      p = query();
      jj_consume_token(SEMICOLON);
      p.print();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CREATE_TABLE:
      case DROP_TABLE:
      case DESC:
      case INSERT:
      case DELETE:
      case SELECT:
      case SHOW_TABLES:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
    }
  }

  static final public PrintMessages query() throws ParseException {
                          PrintMessages p;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CREATE_TABLE:
      p = createTableQuery();
                             {if (true) return p;}
      break;
    case DROP_TABLE:
      p = dropTableQuery();
                           {if (true) return p;}
      break;
    case DESC:
      p = descQuery();
                      {if (true) return p;}
      break;
    case INSERT:
      p = insertQuery();
                        {if (true) return p;}
      break;
    case DELETE:
      p = deleteQuery();
                        {if (true) return p;}
      break;
    case SELECT:
      p = selectQuery();
                        {if (true) return p;}
      break;
    case SHOW_TABLES:
      p = showTablesQuery();
                            {if (true) return p;}
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  static final public PrintMessages createTableQuery() throws ParseException {
                                     String tn; Table t; ArrayList<Column> cl;
    jj_consume_token(CREATE_TABLE);
    tn = tableName();
    if (dbms.isExistingTable(tn)) {
      {if (true) throw new ErrorException(Flags.TABLE_EXISTENCE_ERROR);}
    } else {
      t = new Table(tn);
    }
    tableElementList(t);
    dbms.createTable(t);
    {if (true) return new PrintMessages(Flags.CREATE_TABLE_DONE, tn);}
    throw new Error("Missing return statement in function");
  }

  static final public PrintMessages dropTableQuery() throws ParseException {
                                   String tn;
    jj_consume_token(DROP_TABLE);
    tn = tableName();
    if (!dbms.isExistingTable(tn)) {
      {if (true) throw new ErrorException(Flags.NO_SUCH_TABLE);}
    }

    Table t = dbms.getTable(tn);
    for (Column c: t.getColumns()) {
      if (c.getIsReferenced()) {
        {if (true) throw new ErrorException(Flags.DROP_REFERENCED_TABLE_ERROR, tn);}
      }
    }

    dbms.dropTable(tn);

    {if (true) return new PrintMessages(Flags.DROP_TABLE_DONE, tn);}
    throw new Error("Missing return statement in function");
  }

  static final public PrintMessages descQuery() throws ParseException {
                              String tn;
    jj_consume_token(DESC);
    tn = tableName();
    if (!dbms.isExistingTable(tn)) {
      {if (true) throw new ErrorException(Flags.NO_SUCH_TABLE);}
    }
    dbms.printTable(tn);
    {if (true) return new PrintMessages(Flags.DESC_DONE);}
    throw new Error("Missing return statement in function");
  }

  static final public PrintMessages insertQuery() throws ParseException {
                                String tn; ArrayList<Value> vl;
    jj_consume_token(INSERT);
    tn = tableName();
    vl = insertColumnsAndSource();
    dbms.insertValues(tn, vl);
    {if (true) return new PrintMessages(Flags.INSERT_DONE);}
    throw new Error("Missing return statement in function");
  }

  static final public PrintMessages deleteQuery() throws ParseException {
                                String tn;
    jj_consume_token(DELETE);
    tn = tableName();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case WHERE:
      whereClause();
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    {if (true) return new PrintMessages(Flags.NOTHING);}
    throw new Error("Missing return statement in function");
  }

  static final public PrintMessages selectQuery() throws ParseException {
    jj_consume_token(SELECT);
    selectList();
    tableExpression();
    {if (true) return new PrintMessages(Flags.NOTHING);}
    throw new Error("Missing return statement in function");
  }

  static final public PrintMessages showTablesQuery() throws ParseException {
    jj_consume_token(SHOW_TABLES);
    dbms.showTables();
    {if (true) return new PrintMessages(Flags.SHOW_TABLES_DONE);}
    throw new Error("Missing return statement in function");
  }

  static final public void tableElementList(Table t) throws ParseException {
                                   int key; boolean pk = false;
    jj_consume_token(LEFT_PAREN);
    key = tableElement(t);
    if (key == Flags.PRIMARY_KEY) {
      pk = true;
    }
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_2;
      }
      jj_consume_token(COMMA);
      key = tableElement(t);
      if (key == Flags.PRIMARY_KEY) {
        if (pk == true) {
          {if (true) throw new ErrorException(Flags.DUPLICATE_PRIMARY_KEY_DEF_ERROR);}
        }
        pk = true;
      }
    }
    jj_consume_token(RIGHT_PAREN);
  }

  static final public int tableElement(Table t) throws ParseException {
                              Column c; int key = Flags.NOTHING;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LEGAL_IDENTIFIER:
      columnDefinition(t);
      break;
    case PRIMARY_KEY:
    case FOREIGN_KEY:
      key = tableConstraintDefinition(t);
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return key;}
    throw new Error("Missing return statement in function");
  }

  static final public void columnDefinition(Table t) throws ParseException {
                                   String cn; DataType dt; boolean isNull = true;
    cn = columnName();
    dt = dataType();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT_NULL:
      jj_consume_token(NOT_NULL);
      isNull = false;
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    t.addColumn(new Column(cn, dt, isNull));
  }

  static final public void whereClause() throws ParseException {
    jj_consume_token(WHERE);
    booleanValueExpression();
  }

  static final public void fromClause() throws ParseException {
    jj_consume_token(FROM);
    tableReferenceList();
  }

  static final public void tableReferenceList() throws ParseException {
    referedTable();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      referedTable();
      break;
    default:
      jj_la1[7] = jj_gen;
      ;
    }
  }

  static final public void referedTable() throws ParseException {
    tableName();
    if (jj_2_1(4)) {
      jj_consume_token(AS);
      tableName();
    } else {
      ;
    }
  }

  static final public void booleanValueExpression() throws ParseException {
    booleanTerm();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_3;
      }
      jj_consume_token(OR);
      booleanTerm();
    }
  }

  static final public void booleanTerm() throws ParseException {
    booleanFactor();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        ;
        break;
      default:
        jj_la1[9] = jj_gen;
        break label_4;
      }
      jj_consume_token(AND);
      booleanFactor();
    }
  }

  static final public void booleanFactor() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
      jj_consume_token(NOT);
      break;
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    booleanTest();
  }

  static final public void booleanTest() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LEGAL_IDENTIFIER:
    case INT_VALUE:
    case DATE_VALUE:
    case CHAR_STRING:
      predicate();
      break;
    case LEFT_PAREN:
      parenthesizedBooleanExpression();
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void predicate() throws ParseException {
    if (jj_2_2(4)) {
      comparisonPredicate();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEGAL_IDENTIFIER:
        nullPredicate();
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void comparisonPredicate() throws ParseException {
    compOperand();
    jj_consume_token(COMP_OP);
    compOperand();
  }

  static final public void compOperand() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT_VALUE:
    case DATE_VALUE:
    case CHAR_STRING:
      comparableValue();
      break;
    case LEGAL_IDENTIFIER:
      if (jj_2_3(4)) {
        tableName();
        jj_consume_token(PERIOD);
      } else {
        ;
      }
      columnName();
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void parenthesizedBooleanExpression() throws ParseException {
    jj_consume_token(LEFT_PAREN);
    booleanValueExpression();
    jj_consume_token(RIGHT_PAREN);
  }

  static final public void nullPredicate() throws ParseException {
    if (jj_2_4(4)) {
      tableName();
      jj_consume_token(PERIOD);
    } else {
      ;
    }
    columnName();
    nullOperation();
  }

  static final public void nullOperation() throws ParseException {
    jj_consume_token(IS);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
      jj_consume_token(NOT);
      break;
    default:
      jj_la1[14] = jj_gen;
      ;
    }
    jj_consume_token(NULL);
  }

  static final public int tableConstraintDefinition(Table t) throws ParseException {
                                           ArrayList<String> pkcl; ArrayList<Column> cl;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PRIMARY_KEY:
      pkcl = primaryKeyConstraint();
    // primary key list?óê Ï§ëÎ≥µ ?ûà?äî Í≤ΩÏö∞
    List<String> l = pkcl;
    Set<String> s = new HashSet<String>();
    s.addAll(l);
    if (s.size() != l.size()) {
      {if (true) throw new ErrorException(Flags.DUPLICATE_COLUMN_DEF_ERROR);}
    }
    // column?óê primary key ?Ñ§?†ï, Ï°¥Ïû¨?ïòÏß? ?ïä?äî column?ùº Í≤ΩÏö∞ ?óê?ü¨
    for (String pkc: pkcl) {
      boolean exist = false;
      for (Column c: t.getColumns()) {
        if (c.getName().equals(pkc)) {
          exist = true;
          c.setIsPrimaryKey(true);
          c.setIsNull(false);
          break;
        }
      }
      if (!exist) {
        {if (true) throw new ErrorException(Flags.NON_EXISTING_COLUMN_DEF_ERROR, pkc);}
      }
    }
    {if (true) return Flags.PRIMARY_KEY;}
      break;
    case FOREIGN_KEY:
      referentialConstraint(t);
    {if (true) return Flags.FOREIGN_KEY;}
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public ArrayList<Value> insertColumnsAndSource() throws ParseException {
                                              ArrayList<String> cnl = null; ArrayList<Value> vl;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LEFT_PAREN:
      cnl = columnNameList();
      break;
    default:
      jj_la1[16] = jj_gen;
      ;
    }
    vl = valueList();
    if (cnl != null) {
      if (cnl.size() == vl.size()) {
        for (int i = 0; i < cnl.size(); i++) {
          vl.get(i).setColumnName(cnl.get(i));
        }
      } else {
        {if (true) throw new ErrorException(Flags.INSERT_TYPE_MISMATCH_ERROR);}
      }
    }
    {if (true) return vl;}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayList<Value> valueList() throws ParseException {
                                 Value v;
    ArrayList<Value> vl = new ArrayList<Value>();
    jj_consume_token(VALUES);
    jj_consume_token(LEFT_PAREN);
    v = value();
    vl.add(v);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[17] = jj_gen;
        break label_5;
      }
      jj_consume_token(COMMA);
      v = value();
      vl.add(v);
    }
    jj_consume_token(RIGHT_PAREN);
    {if (true) return vl;}
    throw new Error("Missing return statement in function");
  }

  static final public Value value() throws ParseException {
                  Value v = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NULL:
      jj_consume_token(NULL);
      break;
    case INT_VALUE:
    case DATE_VALUE:
    case CHAR_STRING:
      v = comparableValue();
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return v;}
    throw new Error("Missing return statement in function");
  }

  static final public Value comparableValue() throws ParseException {
                            int iv; String sv; String dv;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT_VALUE:
      jj_consume_token(INT_VALUE);
     iv = Integer.parseInt(token.image);
     {if (true) return new Value(new DataType(Flags.INT, 0), Integer.toString(iv));}
      break;
    case CHAR_STRING:
      jj_consume_token(CHAR_STRING);
    sv = token.image.toLowerCase();
    {if (true) return new Value(new DataType(Flags.CHAR, 0), sv);}
      break;
    case DATE_VALUE:
      jj_consume_token(DATE_VALUE);
    dv = token.image.toLowerCase();
    {if (true) return new Value(new DataType(Flags.DATE, 0), dv);}
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public void tableExpression() throws ParseException {
    fromClause();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case WHERE:
      whereClause();
      break;
    default:
      jj_la1[20] = jj_gen;
      ;
    }
  }

  static final public void selectList() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ALL:
      jj_consume_token(ALL);
      break;
    case LEGAL_IDENTIFIER:
      selectedColumn();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[21] = jj_gen;
          break label_6;
        }
        jj_consume_token(COMMA);
        selectedColumn();
      }
      break;
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void selectedColumn() throws ParseException {
    if (jj_2_5(4)) {
      tableName();
      jj_consume_token(PERIOD);
    } else {
      ;
    }
    columnName();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AS:
      jj_consume_token(AS);
      columnName();
      break;
    default:
      jj_la1[23] = jj_gen;
      ;
    }
  }

  static final public ArrayList<String> primaryKeyConstraint() throws ParseException {
                                             ArrayList<String> pkl;
    jj_consume_token(PRIMARY_KEY);
    pkl = columnNameList();
    {if (true) return pkl;}
    throw new Error("Missing return statement in function");
  }

  static final public void referentialConstraint(Table t) throws ParseException {
                                        ArrayList<String> cnl; String rtn; ArrayList<String> fknl;
    jj_consume_token(FOREIGN_KEY);
    cnl = columnNameList();
    jj_consume_token(REFERENCES);
    rtn = tableName();
    fknl = columnNameList();
    // foreign keyÍ∞? Ï°¥Ïû¨?ïòÏß? ?ïä?äî table?ùÑ Ï∞∏Ï°∞?ïò?äî Í≤ΩÏö∞
    if (!dbms.isExistingTable(rtn)) {
      {if (true) throw new ErrorException(Flags.REFERENCE_TABLE_EXISTENCE_ERROR);}
    }

    // foreign keyÍ∞? Ï∞∏Ï°∞?ïò?äî column?ùò Í∞úÏàòÍ∞? ?ã§Î•? Í≤ΩÏö∞
    if (cnl.size() != fknl.size()) {
      {if (true) throw new ErrorException(Flags.REFERENCE_TYPE_ERROR);}
    }

    String notExistingColumn;
    ArrayList<Column> rcl = new ArrayList<Column>();
    ArrayList<Column> cl = new ArrayList<Column>();

    // foreign keyÍ∞? Ï°¥Ïû¨?ïòÏß? ?ïä?äî column?ùÑ Ï∞∏Ï°∞?ïò?äî Í≤ΩÏö∞
    Table rt = dbms.getTable(rtn);
    notExistingColumn = dbms.compareColumnLists(fknl, rt.getColumns());
    if (notExistingColumn != null) {
      {if (true) throw new ErrorException(Flags.REFERENCE_COLUMN_EXISTENCE_ERROR);}
    }

    // Ï°¥Ïû¨?ïòÏß? ?ïä?äî Ïª¨Îüº?ùÑ foreign keyÎ°? ?†ï?ùò?ïú Í≤ΩÏö∞
    notExistingColumn = dbms.compareColumnLists(cnl, t.getColumns());
    if (notExistingColumn != null) {
      {if (true) throw new ErrorException(Flags.NON_EXISTING_COLUMN_DEF_ERROR, notExistingColumn);}
    }

    int len = cnl.size();
    // Ïß?Î™©Îêú column?ì§ Ï∂îÏ∂ú
    for (int i = 0; i < len; i++) {
      for (Column rc: rt.getColumns()) {
        if (rc.getName().equals(fknl.get(i))) {
          rcl.add(rc);
        }
      }
      for (Column c: t.getColumns()) {
        if (c.getName().equals(cnl.get(i))) {
          cl.add(c);
        }
      }
    }

    // primary keyÍ∞? ?ïÑ?ãå column?ùÑ Ï∞∏Ï°∞?ïò?äî Í≤ΩÏö∞
    for (Column c: cl) {
      if (c.getIsPrimaryKey()) {
        {if (true) throw new ErrorException(Flags.REFERENCE_NON_PRIMARY_KEY_ERROR);}
      }
    }

    // foreign keyÍ∞? Ï∞∏Ï°∞?ïò?äî column?ùò ???ûÖ?ù¥ ?ã§Î•? Í≤ΩÏö∞
    for (int i = 0; i < len; i++) {
      if (!cl.get(i).getDataType().toString().equals(rcl.get(i).getDataType().toString())) {
        {if (true) throw new ErrorException(Flags.REFERENCE_TYPE_ERROR);}
      }
    }

    // column?óê foreign key ?†ïÎ≥? ???û•
    for (int i = 0; i < len; i++) {
      cl.get(i).setIsForeignKey(true);
      cl.get(i).setForeignKey(rt, rcl.get(i));
      rcl.get(i).setIsReferenced(true);
    }
  }

  static final public ArrayList<String> columnNameList() throws ParseException {
                                       ArrayList<String> cl = new ArrayList<String>(); String cn;
    jj_consume_token(LEFT_PAREN);
    cn = columnName();
    cl.add(cn);
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[24] = jj_gen;
        break label_7;
      }
      jj_consume_token(COMMA);
      cn = columnName();
      cl.add(cn);
    }
    jj_consume_token(RIGHT_PAREN);
    {if (true) return cl;}
    throw new Error("Missing return statement in function");
  }

  static final public DataType dataType() throws ParseException {
                        int dt; int cl = 0;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
      jj_consume_token(INT);
    dt = Flags.INT;
    {if (true) return new DataType(dt, cl);}
      break;
    case CHAR:
      jj_consume_token(CHAR);
      dt = Flags.CHAR;
      jj_consume_token(LEFT_PAREN);
      jj_consume_token(INT_VALUE);
      cl = Integer.parseInt(token.image);
      jj_consume_token(RIGHT_PAREN);
      if (cl <= 0) {
        {if (true) throw new ErrorException(Flags.CHAR_LENGTH_ERROR);}
      }
      {if (true) return new DataType(dt, cl);}
      break;
    case DATE:
      jj_consume_token(DATE);
    dt = Flags.DATE;
    {if (true) return new DataType(dt, cl);}
      break;
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public String tableName() throws ParseException {
    jj_consume_token(LEGAL_IDENTIFIER);
    {if (true) return token.image.toLowerCase();}
    throw new Error("Missing return statement in function");
  }

  static final public String columnName() throws ParseException {
    jj_consume_token(LEGAL_IDENTIFIER);
    {if (true) return token.image.toLowerCase();}
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_3R_16() {
    if (jj_scan_token(CHAR_STRING)) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_scan_token(AS)) return true;
    if (jj_3R_8()) return true;
    return false;
  }

  static private boolean jj_3R_9() {
    if (jj_3R_10()) return true;
    if (jj_scan_token(COMP_OP)) return true;
    if (jj_3R_10()) return true;
    return false;
  }

  static private boolean jj_3R_8() {
    if (jj_scan_token(LEGAL_IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_15() {
    if (jj_scan_token(INT_VALUE)) return true;
    return false;
  }

  static private boolean jj_3R_13() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_15()) {
    jj_scanpos = xsp;
    if (jj_3R_16()) {
    jj_scanpos = xsp;
    if (jj_3R_17()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_3R_9()) return true;
    return false;
  }

  static private boolean jj_3_5() {
    if (jj_3R_8()) return true;
    if (jj_scan_token(PERIOD)) return true;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_3R_8()) return true;
    if (jj_scan_token(PERIOD)) return true;
    return false;
  }

  static private boolean jj_3R_12() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) jj_scanpos = xsp;
    if (jj_3R_14()) return true;
    return false;
  }

  static private boolean jj_3R_11() {
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_10() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_11()) {
    jj_scanpos = xsp;
    if (jj_3R_12()) return true;
    }
    return false;
  }

  static private boolean jj_3R_17() {
    if (jj_scan_token(DATE_VALUE)) return true;
    return false;
  }

  static private boolean jj_3R_14() {
    if (jj_scan_token(LEGAL_IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_3R_8()) return true;
    if (jj_scan_token(PERIOD)) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public SimpleDBMSParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[26];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xfe20,0xfe00,0xfe00,0x1000000,0x0,0x400c0000,0x20000,0x0,0x2000000,0x4000000,0x8000000,0xc0000000,0x40000000,0xc0000000,0x8000000,0xc0000,0x0,0x0,0x80010000,0x80000000,0x1000000,0x0,0x60000000,0x400000,0x0,0x1c0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x20,0x0,0x0,0x20,0x0,0x0,0x0,0xb,0x0,0x3,0x0,0x0,0x8,0x20,0x3,0x3,0x0,0x20,0x0,0x0,0x20,0x0,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[5];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public SimpleDBMSParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public SimpleDBMSParser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new SimpleDBMSParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public SimpleDBMSParser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new SimpleDBMSParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public SimpleDBMSParser(SimpleDBMSParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(SimpleDBMSParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[50];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 26; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 50; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 5; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
