/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleDBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int DATE = 8;
  /** RegularExpression Id. */
  int CREATE_TABLE = 9;
  /** RegularExpression Id. */
  int DROP_TABLE = 10;
  /** RegularExpression Id. */
  int DESC = 11;
  /** RegularExpression Id. */
  int INSERT = 12;
  /** RegularExpression Id. */
  int DELETE = 13;
  /** RegularExpression Id. */
  int SELECT = 14;
  /** RegularExpression Id. */
  int SHOW_TABLES = 15;
  /** RegularExpression Id. */
  int NOT_NULL = 16;
  /** RegularExpression Id. */
  int PRIMARY_KEY = 17;
  /** RegularExpression Id. */
  int FOREIGN_KEY = 18;
  /** RegularExpression Id. */
  int REFERENCES = 19;
  /** RegularExpression Id. */
  int SEMICOLON = 20;
  /** RegularExpression Id. */
  int LEFT_PAREN = 21;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 22;
  /** RegularExpression Id. */
  int COMMA = 23;
  /** RegularExpression Id. */
  int UNDERSCORE = 24;
  /** RegularExpression Id. */
  int INT_VALUE = 25;
  /** RegularExpression Id. */
  int SIGN = 26;
  /** RegularExpression Id. */
  int DIGIT = 27;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 28;
  /** RegularExpression Id. */
  int ALPHABET = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"create table\"",
    "\"drop table\"",
    "\"desc\"",
    "\"insert\"",
    "\"delete\"",
    "\"select\"",
    "\"show tables\"",
    "\"not null\"",
    "\"primary key\"",
    "\"foreign key\"",
    "\"references\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"_\"",
    "<INT_VALUE>",
    "<SIGN>",
    "<DIGIT>",
    "<LEGAL_IDENTIFIER>",
    "<ALPHABET>",
  };

}
